CREATE TABLE admin_sso_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    code_hash VARCHAR(64) NOT NULL,
    audience VARCHAR(30) NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    used_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_admin_sso_codes PRIMARY KEY (id),
    CONSTRAINT uk_admin_sso_codes_code_hash UNIQUE (code_hash),
    CONSTRAINT ck_admin_sso_codes_expires_after_created CHECK (expires_at > created_at)
);

CREATE INDEX idx_admin_sso_codes_user_id ON admin_sso_codes (user_id);
CREATE INDEX idx_admin_sso_codes_expires_at ON admin_sso_codes (expires_at);

ALTER TABLE admin_sso_codes
    ADD CONSTRAINT fk_admin_sso_codes_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE;
